version: "2.1"

services:
  mysql80:
    image: mysql:8.0
    container_name: mysql80
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  xqueue:
    container_name: xqueue
    image: edxops/xqueue-dev:latest
    command: tail -f /dev/null
    volumes:
      - ..:/edx/app/xqueue/xqueue
    depends_on:
      - mysql80
    environment:
      RABBIT_HOST: "rabbit"
